imageCredentials:
  create: false
  name: csp-registry-secret # When create is false please specify
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""
  email: "example@gmail.com"

enforcerToken: ""
privileged: true

rbac:
  enabled: false
  roleRef:

gate:
  host: csp-gateway-svc
  port: 3622

image:
  repository: enforcer
  tag: 4.0
  pullPolicy: IfNotPresent

livenessProbe: {}
readinessProbe: {}
nodeSelector: {}
tolerations: []

resources:
  requests:
    memory: "150Mi"
    cpu: "30m"
  limits:
    memory: "300Mi"
    cpu: "60m"
